1 of 2 changes to support bot replays in ggtracker#149
One of two fixes

This one corrects for the error we see here:

sc2reader/engine/plugins/context.py", line 66, in handleTargetUnitCommandEvent
    self.last_target_ability_event[event.player.pid] = event
AttributeError: 'NoneType' object has no attribute 'pid'